name: emr
channels:
  - conda-forge
dependencies:
  - joblib=1.1.0
  - jupyterlab=3.2.4
  - matplotlib=3.5.0
  - nltk=3.6.5
  - numpy=1.21.4
  - pandas=1.3.4
  - pip=21.0.1
  - plotly=5.4.0
  - pytest=6.2.5
  - pytest-cov=3.0.0
  - python=3.8.12
  - scikit-learn=1.0.1
  - scipy=1.7.3
  - seaborn=0.11.2
  - statsmodels=0.13.1
