name: emr_data_analysis
channels:
  - conda-forge
dependencies:
  - dash=2.0.0
  - dash-core-components=2.0.0
  - dash-html-components=2.0.0
  - joblib=1.1.0
  - jupyterlab=3.2.4
  - matplotlib=3.5.0
  - numpy=1.21.4
  - pandas=1.3.4
  - pip=21.0.1
  - plotly=5.4.0
  - python=3.8.12
  - scipy=1.7.3
  - statsmodels=0.13.1
  - pip:
    - python-magic-bin==0.4.14
